apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  annotations:
    harness.io/pipelines: |
      Backstage Deployment: https://app.harness.io/ng/account/k5tAdb-3SYWU9PGQYlfntg/all/orgs/default/projects/backstage/pipelines/backstage/deployments/y05mHkp8TxKE7h1OjQ4w9w/pipeline?storeType=INLINE
  tags:
    - java

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a


